name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'You just submitted your first issue for this project. Thank you for getting involved!'
        pr-message: 'You just made your first pull request. Thank you for following our best practice for code updates!'
